// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	biz "hertz_demo/kitex_gen/biz"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, request *biz.LoginRequest, callOptions ...callopt.Option) (r *biz.LoginResponse, err error)
	LogOut(ctx context.Context, request *biz.LogoutRequest, callOptions ...callopt.Option) (r *biz.LogOutResponse, err error)
	GetUsers(ctx context.Context, callOptions ...callopt.Option) (r []*biz.User, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Login(ctx context.Context, request *biz.LoginRequest, callOptions ...callopt.Option) (r *biz.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, request)
}

func (p *kUserServiceClient) LogOut(ctx context.Context, request *biz.LogoutRequest, callOptions ...callopt.Option) (r *biz.LogOutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LogOut(ctx, request)
}

func (p *kUserServiceClient) GetUsers(ctx context.Context, callOptions ...callopt.Option) (r []*biz.User, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUsers(ctx)
}
